require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Api::RegistriesController do

  # This should return the minimal set of attributes required to create a valid
  # Registry. As you add validations to Registry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RegistriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all registries as @registries" do
      registry = Registry.create! valid_attributes
      get :index, {:format => 'json'}, valid_session
      assigns(:registries).to_a.should eq([registry])
    end
  end

  describe "GET show" do
    it "assigns the requested registry as @registry" do
      registry = Registry.create! valid_attributes
      get :show, {:id => registry.to_param, :format => 'json'}, valid_session
      assigns(:registry).should eq(registry)
    end
  end

  describe "GET new" do
    it "assigns a new registry as @registry" do
      get :new, {:format => 'json'}, valid_session
      assigns(:registry).should be_a_new(Registry)
    end
  end

  describe "GET edit" do
    it "assigns the requested registry as @registry" do
      registry = Registry.create! valid_attributes
      get :edit, {:id => registry.to_param, :format => 'json'}, valid_session
      assigns(:registry).should eq(registry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Registry" do
        expect {
          post :create, {:registry => valid_attributes, :format => 'json'}, valid_session
        }.to change(Registry, :count).by(1)
      end

      it "assigns a newly created registry as @registry" do
        post :create, {:registry => valid_attributes, :format => 'json'}, valid_session
        assigns(:registry).should be_a(Registry)
        assigns(:registry).should be_persisted
      end

      it "redirects to the created registry" do
        post :create, {:registry => valid_attributes, :format => 'json'}, valid_session
        response.body.should == Registry.last.to_json
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved registry as @registry" do
        # Trigger the behavior that occurs when invalid params are submitted
        Registry.any_instance.stub(:save).and_return(false)
        post :create, {:registry => { "name" => "invalid value" }}, valid_session
        assigns(:registry).should be_a_new(Registry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Registry.any_instance.stub(:save).and_return(false)
        post :create, {:registry => { "name" => "invalid value" }}, valid_session
        response.body.should == " " # There are no errors on the object
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested registry" do
        registry = Registry.create! valid_attributes
        # Assuming there are no other registries in the database, this
        # specifies that the Registry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Registry.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => registry.to_param, :registry => { "name" => "MyString" }, :format => 'json'}, valid_session
      end

      it "assigns the requested registry as @registry" do
        registry = Registry.create! valid_attributes
        put :update, {:id => registry.to_param, :registry => valid_attributes, :format => 'json'}, valid_session
        assigns(:registry).should eq(registry)
      end

      it "returns successfully" do
        registry = Registry.create! valid_attributes
        put :update, {:id => registry.to_param, :registry => valid_attributes, :format => 'json'}, valid_session
        response.status.should == 204
        response.body.should == " "
      end
    end

    describe "with invalid params" do
      it "assigns the registry as @registry" do
        registry = Registry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Registry.any_instance.stub(:save).and_return(false)
        put :update, {:id => registry.to_param, :registry => { "name" => "invalid value" }, :format => 'json'}, valid_session
        assigns(:registry).should eq(registry)
      end

      it "returns an unprocessable entity" do
        registry = Registry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Registry.any_instance.stub(:save).and_return(false)
        put :update, {:id => registry.to_param, :registry => { "name" => "invalid value" }, :format => 'json'}, valid_session
        response.status.should == 422
        response.body.should == '{}' # We're not creating any validation errors to return.
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested registry" do
      registry = Registry.create! valid_attributes
      expect {
        delete :destroy, {:id => registry.to_param, :format => 'json'}, valid_session
      }.to change(Registry, :count).by(-1)
    end

    it "responds successfully" do
      registry = Registry.create! valid_attributes
      delete :destroy, {:id => registry.to_param, :format => 'json'}, valid_session
      response.should be_success
    end
  end

end
